name: ElementumIPCheck
version: ${project.version}
main: me.jam.ipcheck.ElementumIPCheck
commands:
  ipc:
    permission: ipcheck.ipc
    permission-message: §cYou do not have permission to use this command.
    description: Shows information about a player.
    usage: /ipc <Player Name | UUID | IP>

permissions:
  ipcheck.*:
    default: op
    children:
      ipcheck.ipc: true
      ipcheck.notify: true
      ipcheck.ipc.clear: true